### ISSUE TITLE
`BorderlessTable` throws an erro when using integer values

### ISSUE THREAD

**Issue by dhondta** [dhondta/python-tinyscript#23]
This was raised by [this issue](https://github.com/dhondta/dronesploit/issues/28) from Sploitkit.

While displaying options with the `BorderlessTable` class, the following error is thrown : 

```
[ - ] object of type 'int' has no len()
Traceback (most recent call last):
   [...]
   File "/usr/local/lib/python3.8/dist-packages/sploitkit/core/components/config.py", line 105, in __str__ BorderlessTable(data, "%s options" % prefix).table
   File "/usr/local/lib/python3.8/dist-packages/tinyscript/helpers/layout.py", line 60, in __init__ if len(v) > 0:
TypeError: object of type 'int' has no len()
```

This comes from a regression bug in [this commit](https://github.com/dhondta/python-tinyscript/commit/0fe93bc95c3fc6a08447c0459ad94d446a107803#diff-d8a14d4fa11ff0c77e671ca8385ddb14791f2890208927cb5c72596d8ce9db08R60).

**Comment by dhondta** [comment]
Solved by commit [7f48760482d84ebcd4e8c0757ef1e1fa03482b13](https://github.com/dhondta/python-tinyscript/commit/7f48760482d84ebcd4e8c0757ef1e1fa03482b13).
