### ISSUE TITLE
error with patchy/api.py

### ISSUE THREAD

**Issue by razorwif** [dhondta/python-tinyscript#25]
Salut :),
petit soucis avec le  def _getlength(self) concernant l'api.py de patchy.

```
File "/usr/local/lib/python3.10/dist-packages/tinyscript-1.26.0-py3.10.egg/tinyscript/helpers/data/utils.py", line 24, in <module>
    patchy.replace(bitstring.Bits._getlength, """
  File "/usr/local/lib/python3.10/dist-packages/patchy/api.py", line 51, in replace
    _assert_ast_equal(current_source, expected_source, func.__name__)
  File "/usr/local/lib/python3.10/dist-packages/patchy/api.py", line 345, in _assert_ast_equal
    raise ValueError(msg)
ValueError: The code of '_getlength' has changed from expected.

The current code is:
def _getlength(self) -> int:
    """Return the length of the bitstring in bits."""
    return self._datastore.bitlength

The expected code is:

def _getlength(self):
    """Return the length of the bitstring in bits."""
    return self._datastore.bitlength  

```

**Comment by dhondta** [comment]
Bonjour @razorwif !
Un grand merci pour avoir mentionné ce problème. Je règle ça de suite ;-)

**Comment by dhondta** [comment]
@razorwif  peux-tu tester et m'indiquer si ça fonctionne chez toi ?

**Comment by razorwif** [comment]
toujours pas :'( 

```
└─# tinyscript new test
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tinyscript-1.26.3-py3.10.egg/tinyscript/helpers/data/utils.py", line 52, in <module>
    patchy.replace(bitstring.Bits._getbin, OLD_CODE % " -> str", NEW_CODE % " -> str")
  File "/usr/local/lib/python3.10/dist-packages/patchy-2.6.0-py3.10.egg/patchy/api.py", line 51, in replace
    _assert_ast_equal(current_source, expected_source, func.__name__)
  File "/usr/local/lib/python3.10/dist-packages/patchy-2.6.0-py3.10.egg/patchy/api.py", line 345, in _assert_ast_equal
    raise ValueError(msg)
ValueError: The code of '_getbin' has changed from expected.
The current code is:
def _getbin(self) -> str:
    """Return interpretation as a binary string."""
    return self._readbin(0, self.len)

The expected code is:

def _getbin(self) -> str:
    """Return interpretation as a binary string."""
    return self._readbin(self.len, 0)

```

**Comment by dhondta** [comment]
Salut @razorwif .
Et ainsi, c'est bon ?

**Comment by razorwif** [comment]
salut,
yes pour patchy ca bug plus :) 
en revanche c'est le mdv markdown :'(

```
 from markdown.util import etree
ImportError: cannot import name 'etree' from 'markdown.util' (/usr/local/lib/python3.10/dist-packages/markdown/util.py)


```

**Comment by dhondta** [comment]
@razorwif  Arf, ça c'est un sacré foutoir ; `mdv` avait déjà un problème de support pour Python3.9+ et a donné un fork `mdv3` pour ça. Et maintenant, `markdown.util.etree` est déprécié en faveur de `xml.etree.ElementTree` dans `markdown`>=3.4. Et comme aucun des deux `mdv` et `mdv3` n'a l'air de réagir aux issues ouverts par des utilisateurs pour demander de régler ça, ma seule solution est de temporairement imposer `markown`<3.4 dans mes requirements.

**Comment by dhondta** [comment]
@razorwif  ça devrait être réglé avec Tinyscript v1.26.5 (que je viens à l'instant d'uploader). Tu peux tester, stp ?

**Comment by razorwif** [comment]
@dhondta , yep j'ai lu ca dans d'autre issue :'(
en revanche, ca fonctionne avec le <3.4.

```
└─# tinyscript new test   
└─# ll               
total 8
-rw-r--r-- 1 root root  510 18 sept. 01:07  test.py

```
